import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/Components/Common/Navbar";
import ReduxProvider from "@/providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevScribe",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={` bg-base-300 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ReduxProvider>
          <nav className="bg-white">
            <Navbar />
          </nav>
<main className="container mx-auto bg-base-300">
          
          <section>{children}</section>
        </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
